export interface StateData {
  code: string;
  name: string;
  regionalName: string;
  capital: string;
  zone: "North" | "South" | "East" | "West" | "North-East" | "Central" | "Islands";
  self_enum_start: string; // YYYY-MM-DD
  self_enum_end: string;
  hlo_start: string;
  hlo_end: string;
  pe_start: string;
  pe_end: string;
  is_snow_bound: boolean;
  population_2011: number;
  projected_pop_2027: number;
  sex_ratio_2011: number; // females per 1000 males
  literacy_rate_2011: number; // percentage
  urban_percentage_2011: number;
  tap_water_pct: number;
  lpg_pct: number;
  electricity_pct: number;
  latrine_pct: number;
}

export interface FAQItem {
  id: string;
  category: "General" | "Phase1_HLO" | "Phase2_PE" | "Self_Enumeration" | "Privacy_Legal" | "Caste_Census" | "Security_Scams";
  question: string;
  answer: string;
  legalReference?: string;
  keywords: string[];
}

export interface MythFactItem {
  id: string;
  myth: string;
  fact: string;
  category: string;
  officialRef: string;
}

export interface CensusQuestionSchema {
  id: string;
  phase: 1 | 2;
  number: number;
  category: string;
  label: string;
  description: string;
  whyAsked: string;
  type: "text" | "number" | "select" | "radio" | "checkbox";
  options?: { value: string; label: string }[];
  isConfidential: boolean;
  validationRule?: string;
}

export const ALL_STATES: StateData[] = [
  {
    code: "GA",
    name: "Goa",
    regionalName: "गोंय",
    capital: "Panaji",
    zone: "West",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1458545,
    projected_pop_2027: 1580000,
    sex_ratio_2011: 973,
    literacy_rate_2011: 88.7,
    urban_percentage_2011: 62.2,
    tap_water_pct: 85.4,
    lpg_pct: 86.8,
    electricity_pct: 98.4,
    latrine_pct: 79.7,
  },
  {
    code: "KA",
    name: "Karnataka",
    regionalName: "ಕರ್ನಾಟಕ",
    capital: "Bengaluru",
    zone: "South",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 61095297,
    projected_pop_2027: 68500000,
    sex_ratio_2011: 973,
    literacy_rate_2011: 75.4,
    urban_percentage_2011: 38.6,
    tap_water_pct: 66.5,
    lpg_pct: 35.8,
    electricity_pct: 90.6,
    latrine_pct: 51.2,
  },
  {
    code: "OD",
    name: "Odisha",
    regionalName: "ଓଡ଼ିଶା",
    capital: "Bhubaneswar",
    zone: "East",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 41974218,
    projected_pop_2027: 46200000,
    sex_ratio_2011: 979,
    literacy_rate_2011: 72.9,
    urban_percentage_2011: 16.7,
    tap_water_pct: 23.1,
    lpg_pct: 12.8,
    electricity_pct: 43.0,
    latrine_pct: 22.0,
  },
  {
    code: "SK",
    name: "Sikkim",
    regionalName: "सिक्किम",
    capital: "Gangtok",
    zone: "North-East",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 610577,
    projected_pop_2027: 690000,
    sex_ratio_2011: 890,
    literacy_rate_2011: 81.4,
    urban_percentage_2011: 25.2,
    tap_water_pct: 85.3,
    lpg_pct: 67.2,
    electricity_pct: 92.5,
    latrine_pct: 87.2,
  },
  {
    code: "MZ",
    name: "Mizoram",
    regionalName: "Mizoram",
    capital: "Aizawl",
    zone: "North-East",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1097206,
    projected_pop_2027: 1250000,
    sex_ratio_2011: 976,
    literacy_rate_2011: 91.3,
    urban_percentage_2011: 52.1,
    tap_water_pct: 58.7,
    lpg_pct: 54.4,
    electricity_pct: 84.2,
    latrine_pct: 91.9,
  },
  {
    code: "AN",
    name: "Andaman & Nicobar Islands",
    regionalName: "अंडमान और निकोबार",
    capital: "Port Blair",
    zone: "Islands",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 380581,
    projected_pop_2027: 430000,
    sex_ratio_2011: 876,
    literacy_rate_2011: 86.6,
    urban_percentage_2011: 37.7,
    tap_water_pct: 85.5,
    lpg_pct: 66.8,
    electricity_pct: 86.1,
    latrine_pct: 68.3,
  },
  {
    code: "LD",
    name: "Lakshadweep",
    regionalName: "ലക്ഷദ്വീപ്",
    capital: "Kavaratti",
    zone: "Islands",
    self_enum_start: "2026-04-01",
    self_enum_end: "2026-04-15",
    hlo_start: "2026-04-16",
    hlo_end: "2026-05-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 64473,
    projected_pop_2027: 720000,
    sex_ratio_2011: 946,
    literacy_rate_2011: 91.8,
    urban_percentage_2011: 78.0,
    tap_water_pct: 78.2,
    lpg_pct: 23.4,
    electricity_pct: 99.7,
    latrine_pct: 97.8,
  },
  {
    code: "DL",
    name: "Delhi (NCT & NDMC)",
    regionalName: "दिल्ली",
    capital: "New Delhi",
    zone: "North",
    self_enum_start: "2026-04-15",
    self_enum_end: "2026-04-30",
    hlo_start: "2026-05-01",
    hlo_end: "2026-05-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 16787941,
    projected_pop_2027: 21500000,
    sex_ratio_2011: 868,
    literacy_rate_2011: 86.2,
    urban_percentage_2011: 97.5,
    tap_water_pct: 81.3,
    lpg_pct: 89.6,
    electricity_pct: 99.1,
    latrine_pct: 89.5,
  },
  {
    code: "MH",
    name: "Maharashtra",
    regionalName: "महाराष्ट्र",
    capital: "Mumbai",
    zone: "West",
    self_enum_start: "2026-05-01",
    self_enum_end: "2026-05-15",
    hlo_start: "2026-05-16",
    hlo_end: "2026-06-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 112374333,
    projected_pop_2027: 126000000,
    sex_ratio_2011: 929,
    literacy_rate_2011: 82.3,
    urban_percentage_2011: 45.2,
    tap_water_pct: 67.9,
    lpg_pct: 43.4,
    electricity_pct: 83.9,
    latrine_pct: 53.1,
  },
  {
    code: "TN",
    name: "Tamil Nadu",
    regionalName: "தமிழ்நாடு",
    capital: "Chennai",
    zone: "South",
    self_enum_start: "2026-05-01",
    self_enum_end: "2026-05-15",
    hlo_start: "2026-05-16",
    hlo_end: "2026-06-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 72147030,
    projected_pop_2027: 76800000,
    sex_ratio_2011: 996,
    literacy_rate_2011: 80.1,
    urban_percentage_2011: 48.4,
    tap_water_pct: 79.8,
    lpg_pct: 48.0,
    electricity_pct: 93.4,
    latrine_pct: 48.3,
  },
  {
    code: "GJ",
    name: "Gujarat",
    regionalName: "ગુજરાત",
    capital: "Gandhinagar",
    zone: "West",
    self_enum_start: "2026-05-01",
    self_enum_end: "2026-05-15",
    hlo_start: "2026-05-16",
    hlo_end: "2026-06-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 60439692,
    projected_pop_2027: 71500000,
    sex_ratio_2011: 919,
    literacy_rate_2011: 78.0,
    urban_percentage_2011: 42.6,
    tap_water_pct: 69.0,
    lpg_pct: 38.3,
    electricity_pct: 90.4,
    latrine_pct: 57.3,
  },
  {
    code: "KL",
    name: "Kerala",
    regionalName: "കേരളം",
    capital: "Thiruvananthapuram",
    zone: "South",
    self_enum_start: "2026-05-15",
    self_enum_end: "2026-05-30",
    hlo_start: "2026-06-01",
    hlo_end: "2026-06-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 33406061,
    projected_pop_2027: 35800000,
    sex_ratio_2011: 1084,
    literacy_rate_2011: 94.0,
    urban_percentage_2011: 47.7,
    tap_water_pct: 29.4,
    lpg_pct: 44.5,
    electricity_pct: 94.4,
    latrine_pct: 95.2,
  },
  {
    code: "AP",
    name: "Andhra Pradesh",
    regionalName: "ఆంధ్రప్రదేశ్",
    capital: "Amaravati",
    zone: "South",
    self_enum_start: "2026-05-15",
    self_enum_end: "2026-05-30",
    hlo_start: "2026-06-01",
    hlo_end: "2026-06-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 49577103,
    projected_pop_2027: 53500000,
    sex_ratio_2011: 993,
    literacy_rate_2011: 67.0,
    urban_percentage_2011: 29.5,
    tap_water_pct: 63.6,
    lpg_pct: 35.1,
    electricity_pct: 92.0,
    latrine_pct: 49.6,
  },
  {
    code: "TG",
    name: "Telangana",
    regionalName: "తెలంగాణ",
    capital: "Hyderabad",
    zone: "South",
    self_enum_start: "2026-05-15",
    self_enum_end: "2026-05-30",
    hlo_start: "2026-06-01",
    hlo_end: "2026-06-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 35003674,
    projected_pop_2027: 38200000,
    sex_ratio_2011: 988,
    literacy_rate_2011: 66.5,
    urban_percentage_2011: 38.9,
    tap_water_pct: 66.0,
    lpg_pct: 41.5,
    electricity_pct: 91.8,
    latrine_pct: 51.5,
  },
  {
    code: "WB",
    name: "West Bengal",
    regionalName: "পশ্চিমবঙ্গ",
    capital: "Kolkata",
    zone: "East",
    self_enum_start: "2026-06-01",
    self_enum_end: "2026-06-15",
    hlo_start: "2026-06-16",
    hlo_end: "2026-07-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 91276115,
    projected_pop_2027: 99600000,
    sex_ratio_2011: 950,
    literacy_rate_2011: 76.3,
    urban_percentage_2011: 31.9,
    tap_water_pct: 30.5,
    lpg_pct: 17.5,
    electricity_pct: 54.5,
    latrine_pct: 58.8,
  },
  {
    code: "UP",
    name: "Uttar Pradesh",
    regionalName: "उत्तर प्रदेश",
    capital: "Lucknow",
    zone: "Central",
    self_enum_start: "2026-06-01",
    self_enum_end: "2026-06-15",
    hlo_start: "2026-06-16",
    hlo_end: "2026-07-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 199812341,
    projected_pop_2027: 235000000,
    sex_ratio_2011: 912,
    literacy_rate_2011: 67.7,
    urban_percentage_2011: 22.3,
    tap_water_pct: 36.1,
    lpg_pct: 22.4,
    electricity_pct: 36.8,
    latrine_pct: 35.7,
  },
  {
    code: "BR",
    name: "Bihar",
    regionalName: "बिहार",
    capital: "Patna",
    zone: "East",
    self_enum_start: "2026-06-01",
    self_enum_end: "2026-06-15",
    hlo_start: "2026-06-16",
    hlo_end: "2026-07-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 104099452,
    projected_pop_2027: 128000000,
    sex_ratio_2011: 918,
    literacy_rate_2011: 61.8,
    urban_percentage_2011: 11.3,
    tap_water_pct: 11.4,
    lpg_pct: 8.1,
    electricity_pct: 16.4,
    latrine_pct: 23.1,
  },
  {
    code: "MP",
    name: "Madhya Pradesh",
    regionalName: "मध्य प्रदेश",
    capital: "Bhopal",
    zone: "Central",
    self_enum_start: "2026-06-15",
    self_enum_end: "2026-06-30",
    hlo_start: "2026-07-01",
    hlo_end: "2026-07-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 72626809,
    projected_pop_2027: 85500000,
    sex_ratio_2011: 931,
    literacy_rate_2011: 69.3,
    urban_percentage_2011: 27.6,
    tap_water_pct: 23.8,
    lpg_pct: 18.0,
    electricity_pct: 67.1,
    latrine_pct: 28.8,
  },
  {
    code: "RJ",
    name: "Rajasthan",
    regionalName: "राजस्थान",
    capital: "Jaipur",
    zone: "North",
    self_enum_start: "2026-06-15",
    self_enum_end: "2026-06-30",
    hlo_start: "2026-07-01",
    hlo_end: "2026-07-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 68548437,
    projected_pop_2027: 81000000,
    sex_ratio_2011: 928,
    literacy_rate_2011: 66.1,
    urban_percentage_2011: 24.9,
    tap_water_pct: 35.8,
    lpg_pct: 21.8,
    electricity_pct: 71.4,
    latrine_pct: 29.6,
  },
  {
    code: "PB",
    name: "Punjab",
    regionalName: "ਪੰਜਾਬ",
    capital: "Chandigarh",
    zone: "North",
    self_enum_start: "2026-07-01",
    self_enum_end: "2026-07-15",
    hlo_start: "2026-07-16",
    hlo_end: "2026-08-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 27743338,
    projected_pop_2027: 30500000,
    sex_ratio_2011: 895,
    literacy_rate_2011: 75.8,
    urban_percentage_2011: 37.5,
    tap_water_pct: 86.8,
    lpg_pct: 64.9,
    electricity_pct: 96.6,
    latrine_pct: 79.3,
  },
  {
    code: "HR",
    name: "Haryana",
    regionalName: "हरियाणा",
    capital: "Chandigarh",
    zone: "North",
    self_enum_start: "2026-07-01",
    self_enum_end: "2026-07-15",
    hlo_start: "2026-07-16",
    hlo_end: "2026-08-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 25351462,
    projected_pop_2027: 29800000,
    sex_ratio_2011: 879,
    literacy_rate_2011: 75.6,
    urban_percentage_2011: 34.9,
    tap_water_pct: 69.3,
    lpg_pct: 49.8,
    electricity_pct: 92.9,
    latrine_pct: 68.6,
  },
  {
    code: "AS",
    name: "Assam",
    regionalName: "অসম",
    capital: "Dispur",
    zone: "North-East",
    self_enum_start: "2026-07-01",
    self_enum_end: "2026-07-15",
    hlo_start: "2026-07-16",
    hlo_end: "2026-08-15",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 31205576,
    projected_pop_2027: 35600000,
    sex_ratio_2011: 958,
    literacy_rate_2011: 72.2,
    urban_percentage_2011: 14.1,
    tap_water_pct: 20.3,
    lpg_pct: 19.0,
    electricity_pct: 37.0,
    latrine_pct: 64.9,
  },
  {
    code: "JH",
    name: "Jharkhand",
    regionalName: "झारखंड",
    capital: "Ranchi",
    zone: "East",
    self_enum_start: "2026-07-15",
    self_enum_end: "2026-07-30",
    hlo_start: "2026-08-01",
    hlo_end: "2026-08-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 32988134,
    projected_pop_2027: 39400000,
    sex_ratio_2011: 948,
    literacy_rate_2011: 66.4,
    urban_percentage_2011: 24.1,
    tap_water_pct: 13.9,
    lpg_pct: 11.2,
    electricity_pct: 45.8,
    latrine_pct: 22.0,
  },
  {
    code: "CG",
    name: "Chhattisgarh",
    regionalName: "छत्तीसगढ़",
    capital: "Raipur",
    zone: "Central",
    self_enum_start: "2026-07-15",
    self_enum_end: "2026-07-30",
    hlo_start: "2026-08-01",
    hlo_end: "2026-08-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 25545198,
    projected_pop_2027: 30100000,
    sex_ratio_2011: 991,
    literacy_rate_2011: 70.3,
    urban_percentage_2011: 23.2,
    tap_water_pct: 17.5,
    lpg_pct: 11.5,
    electricity_pct: 75.3,
    latrine_pct: 24.6,
  },
  // Snow-bound Regions (Special Rollout Calendar)
  {
    code: "LA",
    name: "Ladakh (Snow-bound)",
    regionalName: "ལ་དྭགས",
    capital: "Leh",
    zone: "North",
    self_enum_start: "2026-08-01",
    self_enum_end: "2026-08-15",
    hlo_start: "2026-08-16",
    hlo_end: "2026-09-15",
    pe_start: "2026-09-16", // Snow-bound region early PE
    pe_end: "2026-10-31",
    is_snow_bound: true,
    population_2011: 274289,
    projected_pop_2027: 310000,
    sex_ratio_2011: 869,
    literacy_rate_2011: 77.2,
    urban_percentage_2011: 22.6,
    tap_water_pct: 46.5,
    lpg_pct: 68.2,
    electricity_pct: 88.0,
    latrine_pct: 78.4,
  },
  {
    code: "JK",
    name: "Jammu & Kashmir (Snow-bound areas)",
    regionalName: "جموں و کشمیر",
    capital: "Srinagar / Jammu",
    zone: "North",
    self_enum_start: "2026-08-01",
    self_enum_end: "2026-08-15",
    hlo_start: "2026-08-16",
    hlo_end: "2026-09-15",
    pe_start: "2026-09-16", // Snow-bound PE
    pe_end: "2026-10-31",
    is_snow_bound: true,
    population_2011: 12267013,
    projected_pop_2027: 13900000,
    sex_ratio_2011: 889,
    literacy_rate_2011: 67.2,
    urban_percentage_2011: 27.4,
    tap_water_pct: 42.1,
    lpg_pct: 45.2,
    electricity_pct: 85.1,
    latrine_pct: 51.2,
  },
  {
    code: "HP",
    name: "Himachal Pradesh (Snow-bound areas)",
    regionalName: "हिमाचल प्रदेश",
    capital: "Shimla",
    zone: "North",
    self_enum_start: "2026-08-01",
    self_enum_end: "2026-08-15",
    hlo_start: "2026-08-16",
    hlo_end: "2026-09-15",
    pe_start: "2026-09-16",
    pe_end: "2026-10-31",
    is_snow_bound: true,
    population_2011: 6864602,
    projected_pop_2027: 7600000,
    sex_ratio_2011: 972,
    literacy_rate_2011: 82.8,
    urban_percentage_2011: 10.0,
    tap_water_pct: 87.5,
    lpg_pct: 52.8,
    electricity_pct: 96.8,
    latrine_pct: 69.1,
  },
  {
    code: "UK",
    name: "Uttarakhand (Snow-bound areas)",
    regionalName: "उत्तराखंड",
    capital: "Dehradun",
    zone: "North",
    self_enum_start: "2026-08-01",
    self_enum_end: "2026-08-15",
    hlo_start: "2026-08-16",
    hlo_end: "2026-09-15",
    pe_start: "2026-09-16",
    pe_end: "2026-10-31",
    is_snow_bound: true,
    population_2011: 10086292,
    projected_pop_2027: 11600000,
    sex_ratio_2011: 963,
    literacy_rate_2011: 78.8,
    urban_percentage_2011: 30.2,
    tap_water_pct: 74.2,
    lpg_pct: 54.0,
    electricity_pct: 87.0,
    latrine_pct: 65.8,
  },
  {
    code: "TR",
    name: "Tripura",
    regionalName: "ত্রিপুরা",
    capital: "Agartala",
    zone: "North-East",
    self_enum_start: "2026-08-15",
    self_enum_end: "2026-08-30",
    hlo_start: "2026-09-01",
    hlo_end: "2026-09-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 3673917,
    projected_pop_2027: 4150000,
    sex_ratio_2011: 960,
    literacy_rate_2011: 87.2,
    urban_percentage_2011: 26.2,
    tap_water_pct: 35.8,
    lpg_pct: 27.5,
    electricity_pct: 68.4,
    latrine_pct: 86.0,
  },
  {
    code: "ML",
    name: "Meghalaya",
    regionalName: "Meghalaya",
    capital: "Shillong",
    zone: "North-East",
    self_enum_start: "2026-08-15",
    self_enum_end: "2026-08-30",
    hlo_start: "2026-09-01",
    hlo_end: "2026-09-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 2966889,
    projected_pop_2027: 3400000,
    sex_ratio_2011: 989,
    literacy_rate_2011: 74.4,
    urban_percentage_2011: 20.1,
    tap_water_pct: 39.1,
    lpg_pct: 19.3,
    electricity_pct: 60.9,
    latrine_pct: 62.9,
  },
  {
    code: "MN",
    name: "Manipur",
    regionalName: "মণিপুর",
    capital: "Imphal",
    zone: "North-East",
    self_enum_start: "2026-08-15",
    self_enum_end: "2026-08-30",
    hlo_start: "2026-09-01",
    hlo_end: "2026-09-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 2855794,
    projected_pop_2027: 3250000,
    sex_ratio_2011: 985,
    literacy_rate_2011: 76.9,
    urban_percentage_2011: 29.2,
    tap_water_pct: 37.4,
    lpg_pct: 30.5,
    electricity_pct: 68.3,
    latrine_pct: 89.3,
  },
  {
    code: "NL",
    name: "Nagaland",
    regionalName: "Nagaland",
    capital: "Kohima",
    zone: "North-East",
    self_enum_start: "2026-08-15",
    self_enum_end: "2026-08-30",
    hlo_start: "2026-09-01",
    hlo_end: "2026-09-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1978502,
    projected_pop_2027: 2280000,
    sex_ratio_2011: 931,
    literacy_rate_2011: 79.6,
    urban_percentage_2011: 28.9,
    tap_water_pct: 54.0,
    lpg_pct: 26.2,
    electricity_pct: 66.5,
    latrine_pct: 78.4,
  },
  {
    code: "AR",
    name: "Arunachal Pradesh",
    regionalName: "अरुणाचल प्रदेश",
    capital: "Itanagar",
    zone: "North-East",
    self_enum_start: "2026-08-15",
    self_enum_end: "2026-08-30",
    hlo_start: "2026-09-01",
    hlo_end: "2026-09-30",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1383727,
    projected_pop_2027: 1620000,
    sex_ratio_2011: 938,
    literacy_rate_2011: 65.4,
    urban_percentage_2011: 22.9,
    tap_water_pct: 65.4,
    lpg_pct: 35.8,
    electricity_pct: 65.7,
    latrine_pct: 61.3,
  },
  {
    code: "PY",
    name: "Puducherry",
    regionalName: "புதுச்சேரி",
    capital: "Puducherry",
    zone: "South",
    self_enum_start: "2026-04-15",
    self_enum_end: "2026-04-30",
    hlo_start: "2026-05-01",
    hlo_end: "2026-05-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1247953,
    projected_pop_2027: 1520000,
    sex_ratio_2011: 1037,
    literacy_rate_2011: 85.8,
    urban_percentage_2011: 68.3,
    tap_water_pct: 95.8,
    lpg_pct: 82.3,
    electricity_pct: 97.7,
    latrine_pct: 79.1,
  },
  {
    code: "CH",
    name: "Chandigarh",
    regionalName: "ਚੰਡੀਗੜ੍ਹ",
    capital: "Chandigarh",
    zone: "North",
    self_enum_start: "2026-04-15",
    self_enum_end: "2026-04-30",
    hlo_start: "2026-05-01",
    hlo_end: "2026-05-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 1055450,
    projected_pop_2027: 1260000,
    sex_ratio_2011: 818,
    literacy_rate_2011: 86.0,
    urban_percentage_2011: 97.2,
    tap_water_pct: 96.2,
    lpg_pct: 89.2,
    electricity_pct: 98.4,
    latrine_pct: 87.6,
  },
  {
    code: "DN",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    regionalName: "દાદરા અને નગર હવેલી અને દમણ અને દીવ",
    capital: "Daman",
    zone: "West",
    self_enum_start: "2026-04-15",
    self_enum_end: "2026-04-30",
    hlo_start: "2026-05-01",
    hlo_end: "2026-05-31",
    pe_start: "2027-02-09",
    pe_end: "2027-02-28",
    is_snow_bound: false,
    population_2011: 586956,
    projected_pop_2027: 740000,
    sex_ratio_2011: 774,
    literacy_rate_2011: 81.0,
    urban_percentage_2011: 58.0,
    tap_water_pct: 78.4,
    lpg_pct: 54.2,
    electricity_pct: 97.8,
    latrine_pct: 68.9,
  }
];

export const FAQ_KNOWLEDGE_BASE: FAQItem[] = [
  {
    id: "faq-01",
    category: "General",
    question: "What is Census 2027 and why is it historic?",
    answer: "Census 2027 is India's 16th National Census and the 8th since Independence. It is historic because it is India's first 100% digital census (no paper forms), features an online self-enumeration option in 16 languages, and includes the first caste census since 1931 during Phase II.",
    legalReference: "Census Act, 1948; ORGI Notification 2026",
    keywords: ["what is census", "history", "first digital", "caste census", "16th census"]
  },
  {
    id: "faq-02",
    category: "General",
    question: "What are the two phases of Census 2027?",
    answer: "Phase I is the House Listing and Housing Census (HLO), conducted state-wise between 1 April and 30 September 2026, recording 31 questions on housing conditions, amenities, and assets. Phase II is the Population Enumeration (PE), conducted in February 2027 (reference date 1 March 2027), recording individual demographic, economic, and caste details.",
    legalReference: "ORGI Schedule Guidelines 2026-2027",
    keywords: ["two phases", "phase 1", "phase 2", "HLO", "PE", "difference"]
  },
  {
    id: "faq-03",
    category: "General",
    question: "What is the reference date for Census 2027?",
    answer: "The national reference date is 00:00 hours on 1 March 2027. For non-synchronous, snow-bound regions (Ladakh, Jammu & Kashmir, Himachal Pradesh, Uttarakhand), the reference date is 00:00 hours on 1 October 2026.",
    legalReference: "ORGI Reference Date Notification",
    keywords: ["reference date", "snow bound", "1 march 2027", "1 october 2026"]
  },
  {
    id: "faq-04",
    category: "Self_Enumeration",
    question: "What is Self-Enumeration and how does it work?",
    answer: "Self-enumeration allows citizens to fill their household data online via the official portal in any of the 16 scheduled languages during a 15-day window before the enumerator visits. Once submitted, the citizen receives a Self-Enumeration ID/QR code. When the enumerator visits, you simply share this ID for instant digital verification.",
    legalReference: "Census Rules (Amendment) on Digital Submission",
    keywords: ["self enumeration", "online fill", "15 day window", "self enum id", "qr code"]
  },
  {
    id: "faq-05",
    category: "Self_Enumeration",
    question: "Is Self-Enumeration mandatory, or can I wait for the enumerator?",
    answer: "Self-enumeration is optional and designed for your convenience. If you do not self-enumerate online, an authorized government enumerator with an official mobile tablet/app will visit your home and record your answers directly.",
    legalReference: "Census Act 1948 Section 10",
    keywords: ["is self enumeration mandatory", "optional", "enumerator visit", "tablet"]
  },
  {
    id: "faq-06",
    category: "Privacy_Legal",
    question: "Is my personal Census data shared with tax, police, or private companies?",
    answer: "No. Under Section 15 of the Census Act, 1948, all individual census records are strictly confidential and cannot be accessed by tax authorities, police, courts, or private corporations. They cannot be used as evidence in any civil or criminal proceeding. Only anonymized, aggregated statistical tables are published.",
    legalReference: "Census Act 1948, Section 15 (Confidentiality of records)",
    keywords: ["confidentiality", "tax", "police", "court", "evidence", "privacy", "section 15"]
  },
  {
    id: "faq-07",
    category: "Privacy_Legal",
    question: "Is Aadhaar number mandatory for Census 2027?",
    answer: "No. Aadhaar number is NOT mandatory for Census 2027. You do NOT need to give your Aadhaar card or biometric scans. Only a mobile number is requested for sending your Self-Enumeration confirmation and census SMS updates.",
    legalReference: "ORGI Privacy Safeguards 2026",
    keywords: ["aadhaar mandatory", "aadhaar number", "biometrics", "mobile number"]
  },
  {
    id: "faq-08",
    category: "Security_Scams",
    question: "Is there any fee or payment required for Census self-enumeration?",
    answer: "ABSOLUTELY NO. The Census of India is 100% FREE. The government never asks for money, processing fees, UPI payments, credit card info, or bank details. Any message asking for money to update census data is a fraudulent SCAM.",
    legalReference: "PIB Fact Check Advisory on Census Scams",
    keywords: ["fee", "payment", "cost", "money", "free", "scam", "upi", "bank account"]
  },
  {
    id: "faq-09",
    category: "Security_Scams",
    question: "How do I identify a genuine Census enumerator?",
    answer: "Genuine enumerators are government teachers/officials carrying an official photo ID card issued by ORGI/District Collector, a QR-verified authorization letter, and an official Census 2027 mobile device. They will NEVER ask for bank passwords, OTPs, or fees.",
    legalReference: "ORGI Enumerator Protocol Guidelines",
    keywords: ["identify enumerator", "id card", "fake enumerator", "authorization"]
  },
  {
    id: "faq-10",
    category: "Caste_Census",
    question: "What is the Caste Census in Phase II (2027)?",
    answer: "In Phase II (Population Enumeration in February 2027), the census includes comprehensive caste enumeration for the first time since 1931, alongside Scheduled Castes (SC) and Scheduled Tribes (ST) data, to accurately understand demographic and socio-economic distributions for inclusive policymaking.",
    legalReference: "Ministry of Home Affairs 2026 Resolution",
    keywords: ["caste census", "1931", "sc", "st", "obc", "general", "demographics"]
  },
  {
    id: "faq-11",
    category: "Phase1_HLO",
    question: "What 31 questions are asked during Phase I House Listing (HLO)?",
    answer: "Phase I collects 31 questions covering: Building number, house materials (roof/wall/floor), condition of house, total persons living, name & sex of head, SC/ST/Other status, ownership of house, number of rooms, drinking water source & availability, lighting source, toilet access & type, wastewater drainage, bathing facility, cooking fuel & LPG connection, and household assets (Radio, TV, Laptop/Computer, Internet, Phone/Smartphone, Bicycle/Scooter/Car, Cereal consumed).",
    legalReference: "Gazette Notification on Census HLO Schedule",
    keywords: ["31 questions", "phase 1 questions", "housing questions", "assets", "amenities"]
  },
  {
    id: "faq-12",
    category: "General",
    question: "What 16 languages are supported in the Digital Census portal?",
    answer: "The official portal and Jan Ganana AI support 16 languages: Hindi, English, Bengali, Telugu, Marathi, Tamil, Gujarati, Urdu, Kannada, Odia, Malayalam, Punjabi, Assamese, Maithili, Santali, and Sanskrit.",
    legalReference: "Schedule VIII Constitution of India & ORGI i18n portal",
    keywords: ["16 languages", "regional languages", "hindi", "tamil", "bengali", "telugu"]
  },
  {
    id: "faq-13",
    category: "Privacy_Legal",
    question: "How does DPDP Act 2023 apply to digital citizen assistance?",
    answer: "Under the Digital Personal Data Protection (DPDP) Act 2023, Jan Ganana AI enforces purpose limitation, data minimization, explicit consent recording, zero storage of plain-text PII, transparent 'My Data' viewing, and one-click 'Right to Erasure'.",
    legalReference: "Digital Personal Data Protection Act, 2023",
    keywords: ["dpdp act", "data protection", "right to erasure", "consent", "my data"]
  }
];

export const MYTHS_AND_FACTS: MythFactItem[] = [
  {
    id: "myth-01",
    myth: "Census 2027 requires paying a ₹50 or ₹100 registration fee online.",
    fact: "Census 2027 is 100% free of cost. The government never charges any fee for self-enumeration or enumerator visits. Any payment link is a scam.",
    category: "Financial / Scams",
    officialRef: "PIB Fact Check Bulletin 2026"
  },
  {
    id: "myth-02",
    myth: "Aadhaar card and biometric thumbprints are mandatory for census registration.",
    fact: "No biometrics or Aadhaar cards are collected for Census 2027. Census is not Aadhaar enrollment.",
    category: "Documents & Privacy",
    officialRef: "ORGI Press Release, Ministry of Home Affairs"
  },
  {
    id: "myth-03",
    myth: "Census answers will be shared with the Income Tax department to check tax evasion.",
    fact: "Under Section 15 of the Census Act 1948, census data is strictly confidential and completely barred from being shared with tax, police, or judicial authorities.",
    category: "Legal Protection",
    officialRef: "Census Act 1948, Section 15"
  },
  {
    id: "myth-04",
    myth: "If I don't self-enumerate online within 15 days, I will be fined or left out of the census.",
    fact: "Self-enumeration is completely optional for citizen convenience. If you don't fill online, an authorized government enumerator will visit your house.",
    category: "Process",
    officialRef: "ORGI Citizens' Guide 2026"
  },
  {
    id: "myth-05",
    myth: "Enumerators will ask for bank account numbers, ATM pins, or OTPs to credit welfare funds.",
    fact: "Enumerators NEVER ask for bank details, credit cards, or OTPs. Census is solely statistical demographic enumeration, not a direct bank transfer scheme.",
    category: "Financial / Scams",
    officialRef: "MHA Cyber Crime Portal Warning"
  },
  {
    id: "myth-06",
    myth: "Snow-bound regions in Himalayas are covered at the same time as Delhi and Mumbai.",
    fact: "Snow-bound areas (Ladakh, J&K, Himachal Pradesh, Uttarakhand) have a separate non-synchronous calendar (Sep–Oct 2026) due to severe winter weather.",
    category: "Schedule & Geography",
    officialRef: "ORGI Non-Synchronous Rollout Directive"
  }
];

export const HLO_31_QUESTIONS: CensusQuestionSchema[] = [
  {
    id: "q1",
    phase: 1,
    number: 1,
    category: "Building & Census House",
    label: "Building Number (Municipal or Local Authority Number)",
    description: "The official door number or municipal building number assigned to the structure.",
    whyAsked: "Helps geo-locate and uniquely identify physical housing structures on GIS maps.",
    type: "text",
    isConfidential: true,
  },
  {
    id: "q2",
    phase: 1,
    number: 2,
    category: "Building & Census House",
    label: "Census House Number",
    description: "Unique sub-number within the building if divided into separate living units.",
    whyAsked: "Ensures every distinct dwelling unit within a building is counted accurately.",
    type: "text",
    isConfidential: true,
  },
  {
    id: "q3",
    phase: 1,
    number: 3,
    category: "Housing Material",
    label: "Predominant Material of Floor",
    description: "What is the floor of this house primarily made of?",
    whyAsked: "Key indicator of structural housing quality and socio-economic wellbeing.",
    type: "select",
    options: [
      { value: "mud", label: "Mud / Earth" },
      { value: "wood", label: "Wood / Bamboo" },
      { value: "burnt_brick", label: "Burnt Brick / Stone" },
      { value: "cement", label: "Cement" },
      { value: "mosaic_tiles", label: "Mosaic / Floor Tiles / Marble" },
      { value: "other", label: "Other material" }
    ],
    isConfidential: false,
  },
  {
    id: "q4",
    phase: 1,
    number: 4,
    category: "Housing Material",
    label: "Predominant Material of Wall",
    description: "What material are the external walls mainly made of?",
    whyAsked: "Evaluates disaster vulnerability and pucca/kutcha classification.",
    type: "select",
    options: [
      { value: "grass_thatch", label: "Grass / Thatch / Bamboo" },
      { value: "mud_unburnt_brick", label: "Mud / Unburnt Brick" },
      { value: "wood", label: "Wood" },
      { value: "burnt_brick", label: "Burnt Brick / Concrete blocks" },
      { value: "stone", label: "Stone" },
      { value: "concrete", label: "Reinforced Concrete (RCC)" },
      { value: "other", label: "Other" }
    ],
    isConfidential: false,
  },
  {
    id: "q5",
    phase: 1,
    number: 5,
    category: "Housing Material",
    label: "Predominant Material of Roof",
    description: "What is the main roof cover made of?",
    whyAsked: "Assesses durability, safety against rain/cyclones, and thermal insulation.",
    type: "select",
    options: [
      { value: "grass_thatch", label: "Grass / Thatch / Reeds / Wood" },
      { value: "tiles_slate", label: "Handmade / Machine Tiles / Slate" },
      { value: "metal_asbestos", label: "Corrugated Iron / Metal / Asbestos Sheets" },
      { value: "brick_lime", label: "Brick / Lime stone" },
      { value: "concrete_rcc", label: "Concrete (RCC)" },
      { value: "other", label: "Other" }
    ],
    isConfidential: false,
  },
  {
    id: "q6",
    phase: 1,
    number: 6,
    category: "House Use & Condition",
    label: "Usage of this Census House",
    description: "Is this house used for residence, shop, workshop, school, or mixed use?",
    whyAsked: "Distinguishes residential dwellings from commercial/institutional structures.",
    type: "select",
    options: [
      { value: "residence_only", label: "Residence only" },
      { value: "residence_other", label: "Residence with other use (shop/workshop)" },
      { value: "vacant", label: "Vacant" },
      { value: "other", label: "Non-residential" }
    ],
    isConfidential: false,
  },
  {
    id: "q7",
    phase: 1,
    number: 7,
    category: "House Use & Condition",
    label: "Condition of this Census House",
    description: "Overall structural state of the house.",
    whyAsked: "Assists urban/rural housing shortage calculations and redevelopment schemes (PMAY).",
    type: "select",
    options: [
      { value: "good", label: "Good (no major repairs needed)" },
      { value: "livable", label: "Livable (minor repairs needed)" },
      { value: "dilapidated", label: "Dilapidated (in bad/dangerous shape)" }
    ],
    isConfidential: false,
  },
  {
    id: "q8",
    phase: 1,
    number: 8,
    category: "Household Demographics",
    label: "Household Number",
    description: "Serial number of household residing in this house.",
    whyAsked: "Multiple households can share a single census house.",
    type: "number",
    isConfidential: true,
  },
  {
    id: "q9",
    phase: 1,
    number: 9,
    category: "Household Demographics",
    label: "Total Number of Persons Normally Residing",
    description: "How many members normally stay in this household?",
    whyAsked: "Fundamental denominator for household size and per-capita amenity planning.",
    type: "number",
    isConfidential: true,
  },
  {
    id: "q10",
    phase: 1,
    number: 10,
    category: "Household Demographics",
    label: "Name of the Head of the Household",
    description: "Full name of the person recognized as head by family members.",
    whyAsked: "Primary identifier for household record link in Phase II.",
    type: "text",
    isConfidential: true,
  },
  {
    id: "q11",
    phase: 1,
    number: 11,
    category: "Household Demographics",
    label: "Sex of the Head of Household",
    description: "Male, Female, or Transgender.",
    whyAsked: "Tracks female-headed households for targeted social safety net policies.",
    type: "select",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "transgender", label: "Transgender" }
    ],
    isConfidential: false,
  },
  {
    id: "q12",
    phase: 1,
    number: 12,
    category: "Household Demographics",
    label: "Social Category (SC / ST / Other)",
    description: "Does the head of household belong to SC, ST, or Other category?",
    whyAsked: "Constitutional requirement for statutory planning for SC/ST populations.",
    type: "select",
    options: [
      { value: "sc", label: "Scheduled Caste (SC)" },
      { value: "st", label: "Scheduled Tribe (ST)" },
      { value: "other", label: "Other" }
    ],
    isConfidential: false,
  },
  {
    id: "q13",
    phase: 1,
    number: 13,
    category: "Ownership & Living Space",
    label: "Ownership Status of the House",
    description: "Is this house owned, rented, or other?",
    whyAsked: "Monitors homeownership rates vs rental housing demand.",
    type: "select",
    options: [
      { value: "owned", label: "Owned" },
      { value: "rented", label: "Rented" },
      { value: "other", label: "Any other arrangement" }
    ],
    isConfidential: false,
  },
  {
    id: "q14",
    phase: 1,
    number: 14,
    category: "Ownership & Living Space",
    label: "Number of Dwelling Rooms Exclusively in Possession",
    description: "Count rooms used for living/sleeping (excluding kitchen/bathroom/corridor).",
    whyAsked: "Measures congestion and room-density metrics across India.",
    type: "number",
    isConfidential: false,
  },
  {
    id: "q15",
    phase: 1,
    number: 15,
    category: "Ownership & Living Space",
    label: "Number of Married Couples Living in Household",
    description: "Total count of married couples residing in this house.",
    whyAsked: "Assesses privacy, joint family structures, and new housing unit requirements.",
    type: "number",
    isConfidential: false,
  },
  {
    id: "q16",
    phase: 1,
    number: 16,
    category: "Water & Sanitation",
    label: "Main Source of Drinking Water",
    description: "Where does the household get primary drinking water from?",
    whyAsked: "Tracks piped water coverage under Jal Jeevan Mission.",
    type: "select",
    options: [
      { value: "tap_treated", label: "Tap water from treated source (Piped)" },
      { value: "tap_untreated", label: "Tap water from untreated source" },
      { value: "covered_well", label: "Covered well" },
      { value: "uncovered_well", label: "Uncovered well" },
      { value: "handpump", label: "Hand pump / Borewell" },
      { value: "river_canal", label: "River / Canal / Spring / Tank" },
      { value: "other", label: "Other" }
    ],
    isConfidential: false,
  },
  {
    id: "q17",
    phase: 1,
    number: 17,
    category: "Water & Sanitation",
    label: "Availability of Drinking Water Source",
    description: "Within premises, near premises (within 100m/500m), or away?",
    whyAsked: "Monitors time burden of fetching water, especially for women.",
    type: "select",
    options: [
      { value: "within_premises", label: "Within the premises" },
      { value: "near_premises", label: "Near the premises (< 100m urban / < 500m rural)" },
      { value: "away", label: "Away from premises" }
    ],
    isConfidential: false,
  },
  {
    id: "q18",
    phase: 1,
    number: 18,
    category: "Power & Lighting",
    label: "Main Source of Lighting",
    description: "What is the primary lighting power source?",
    whyAsked: "Measures 100% household electrification and grid reliability (Saubhagya).",
    type: "select",
    options: [
      { value: "electricity", label: "Electricity (Grid power)" },
      { value: "solar", label: "Solar Energy" },
      { value: "kerosene", label: "Kerosene" },
      { value: "other_oil", label: "Other oil" },
      { value: "no_lighting", label: "No lighting" }
    ],
    isConfidential: false,
  },
  {
    id: "q19",
    phase: 1,
    number: 19,
    category: "Water & Sanitation",
    label: "Access to Latrine Facility",
    description: "Does the household have access to a toilet facility?",
    whyAsked: "Measures Open Defecation Free (ODF) sustainability under Swachh Bharat Mission.",
    type: "select",
    options: [
      { value: "within_premises", label: "Flush / Pour flush within premises" },
      { value: "community_toilet", label: "Community / Public latrine" },
      { value: "open", label: "No latrine (Open area / Field)" }
    ],
    isConfidential: false,
  },
  {
    id: "q20",
    phase: 1,
    number: 20,
    category: "Water & Sanitation",
    label: "Type of Latrine Facility",
    description: "Piped sewer, septic tank, twin-pit, or other system?",
    whyAsked: "Evaluates sewage management and environmental health.",
    type: "select",
    options: [
      { value: "sewer_system", label: "Piped sewer system" },
      { value: "septic_tank", label: "Septic tank" },
      { value: "pit_latrine", label: "Twin pit / Single pit latrine" },
      { value: "other", label: "Other" }
    ],
    isConfidential: false,
  },
  {
    id: "q21",
    phase: 1,
    number: 21,
    category: "Water & Sanitation",
    label: "Wastewater Drainage Outlet",
    description: "Is wastewater connected to a closed drainage, open drain, or no drain?",
    whyAsked: "Guides urban sanitation and stormwater drainage infrastructure.",
    type: "select",
    options: [
      { value: "closed_drain", label: "Closed drainage (Underground)" },
      { value: "open_drain", label: "Open drain" },
      { value: "no_drain", label: "No drainage outlet" }
    ],
    isConfidential: false,
  },
  {
    id: "q22",
    phase: 1,
    number: 22,
    category: "Water & Sanitation",
    label: "Bathing Facility Availability",
    description: "Bathroom and enclosure availability within premises.",
    whyAsked: "Assesses personal hygiene and domestic dignity indicators.",
    type: "select",
    options: [
      { value: "bathroom_with_roof", label: "Bathroom with roof within premises" },
      { value: "enclosure_no_roof", label: "Enclosure without roof within premises" },
      { value: "none", label: "No bathing facility within premises" }
    ],
    isConfidential: false,
  },
  {
    id: "q23",
    phase: 1,
    number: 23,
    category: "Kitchen & Cooking Fuel",
    label: "Availability of Kitchen and LPG/PNG Connection",
    description: "Cooking area status and clean cooking gas availability.",
    whyAsked: "Measures PM Ujjwala Yojana clean fuel coverage and indoor air pollution.",
    type: "select",
    options: [
      { value: "cooking_inside_lpg", label: "Cooking inside house with LPG/PNG connection" },
      { value: "cooking_inside_no_lpg", label: "Cooking inside house without LPG/PNG" },
      { value: "cooking_outside", label: "Cooking outside house" },
      { value: "no_cooking", label: "No cooking facility" }
    ],
    isConfidential: false,
  },
  {
    id: "q24",
    phase: 1,
    number: 24,
    category: "Kitchen & Cooking Fuel",
    label: "Main Fuel Used for Cooking",
    description: "LPG, Firewood, Crop residue, Cowdung, Biogas, Kerosene, Electricity?",
    whyAsked: "Tracks transition from solid biomass to clean modern fuels.",
    type: "select",
    options: [
      { value: "lpg_png", label: "LPG / Piped Natural Gas (PNG)" },
      { value: "electricity", label: "Electricity / Induction" },
      { value: "biogas", label: "Biogas" },
      { value: "firewood", label: "Firewood" },
      { value: "crop_cowdung", label: "Crop residue / Cowdung cake" },
      { value: "coal_charcoal", label: "Coal / Charcoal" },
      { value: "kerosene", label: "Kerosene" }
    ],
    isConfidential: false,
  },
  {
    id: "q25",
    phase: 1,
    number: 25,
    category: "Household Assets",
    label: "Availability of Radio / Transistor",
    description: "Does any member of the household possess a radio or transistor?",
    whyAsked: "Historical tracking of broadcast media penetration in rural/remote zones.",
    type: "radio",
    options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }],
    isConfidential: false,
  },
  {
    id: "q26",
    phase: 1,
    number: 26,
    category: "Household Assets",
    label: "Availability of Television",
    description: "Does the household own a TV?",
    whyAsked: "Key durable consumer asset metric.",
    type: "radio",
    options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }],
    isConfidential: false,
  },
  {
    id: "q27",
    phase: 1,
    number: 27,
    category: "Household Assets",
    label: "Availability of Internet Access",
    description: "Does anyone in household have active internet access (broadband or mobile data)?",
    whyAsked: "Vital for measuring the Digital India revolution and rural connectivity.",
    type: "radio",
    options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }],
    isConfidential: false,
  },
  {
    id: "q28",
    phase: 1,
    number: 28,
    category: "Household Assets",
    label: "Availability of Laptop / Computer",
    description: "Desktop, laptop, or tablet computer in household.",
    whyAsked: "Tracks educational computing assets and digital literacy readiness.",
    type: "select",
    options: [
      { value: "laptop_with_internet", label: "Yes (with Internet connection)" },
      { value: "laptop_no_internet", label: "Yes (without Internet connection)" },
      { value: "none", label: "No" }
    ],
    isConfidential: false,
  },
  {
    id: "q29",
    phase: 1,
    number: 29,
    category: "Household Assets",
    label: "Availability of Telephone / Mobile / Smartphone",
    description: "Landline, feature phone, or smartphone ownership.",
    whyAsked: "Monitors mobile tele-density and smartphone diffusion across economic tiers.",
    type: "select",
    options: [
      { value: "smartphone", label: "Smartphone" },
      { value: "feature_mobile", label: "Mobile (Basic / Feature phone only)" },
      { value: "landline_only", label: "Landline phone only" },
      { value: "both", label: "Both Landline and Mobile" },
      { value: "none", label: "None" }
    ],
    isConfidential: false,
  },
  {
    id: "q30",
    phase: 1,
    number: 30,
    category: "Household Assets",
    label: "Availability of Vehicles / Transport Assets",
    description: "Bicycle, Scooter/Motorcycle, Car/Jeep/Van.",
    whyAsked: "Indicator of mobility, transport access, and economic prosperity.",
    type: "checkbox",
    options: [
      { value: "bicycle", label: "Bicycle" },
      { value: "scooter_bike", label: "Scooter / Motorcycle / Moped" },
      { value: "car_van", label: "Car / Jeep / Van" },
      { value: "none", label: "None of these" }
    ],
    isConfidential: false,
  },
  {
    id: "q31",
    phase: 1,
    number: 31,
    category: "Communication & Verification",
    label: "Mobile Number for Census Communication",
    description: "Mobile number of head or respondent for census confirmation SMS.",
    whyAsked: "Used strictly by ORGI for sending Self-Enumeration Reference SMS.",
    type: "text",
    isConfidential: true,
    validationRule: "^[6-9]\\d{9}$",
  }
];
