/**
 * Static English translation dictionary for the Census 2027 Practice Wizard.
 * Extracted from page.tsx to keep component files focused on rendering logic.
 * These strings are dynamically translated at runtime via Gemini for 16 languages.
 */
export const WIZARD_PAGE_ENGLISH: Record<string, string> = {
  headerBadge: "Official Practice Simulator • 31 HLO Questions",
  step1: "Location & Head",
  step2: "Housing Structure",
  step3: "Water & Fuel",
  step4: "Assets & Members",
  step5: "Practice Slip",
  step1Heading: "Step 1: Household Location & Head of Household",
  step2Heading: "Step 2: Housing Material, Ownership & Living Space",
  step3Heading: "Step 3: Drinking Water, Sanitation, Lighting & Fuel",
  step4Heading: "Step 4: Digital Assets & Household Member Roster",
  step5Heading: "Step 5: Simulation Complete & Practice Reference Slip",
  stateLabel: "State / UT",
  districtLabel: "District",
  buildingLabel: "Building / Door No.",
  censusHouseLabel: "Census House Sub-Number",
  headNameLabel: "Name of Head of Household",
  headSexLabel: "Sex of Head",
  socialCategoryLabel: "Social Category of Head (SC / ST / Other)",
  mobileLabel: "Head Mobile Number (For Digital Census Verification)",
  floorLabel: "Predominant Floor Material",
  wallLabel: "Predominant Wall Material",
  roofLabel: "Predominant Roof Material",
  ownershipLabel: "Ownership Status of Census House",
  roomsLabel: "Number of Dwelling Rooms",
  couplesLabel: "Number of Married Couples",
  waterSourceLabel: "Main Source of Drinking Water",
  waterAvailLabel: "Availability of Drinking Water Source",
  lightingLabel: "Main Source of Lighting",
  latrineLabel: "Type of Latrine Facility",
  drainageLabel: "Waste Water Drainage System",
  kitchenLabel: "Availability of Kitchen with LPG/PNG",
  fuelLabel: "Main Fuel Used for Cooking",
  assetsHeading: "Select Household Assets (Radio, TV, Internet, Vehicle):",
  membersHeading: "Household Member Details:",
  addMemberBtn: "+ Add Family Member",
  btnNext: "Next Step",
  btnPrev: "Previous Step",
  btnSubmit: "Finalize Practice & Generate Slip",
  certTitle: "Digital Census 2027 Practice Enumeration Slip",
  certSubtitle:
    "Practice & Awareness simulation only. No real data submitted to government servers.",
  refCodeLabel: "Practice Reference Code:",
  printBtn: "Print Practice Slip",
  practiceAgainBtn: "Practice Again",
};

/** Default form data for a pre-filled practice session */
export const DEFAULT_FORM_DATA: Record<string, string | number> = {
  stateCode: "GA",
  districtName: "North Goa",
  buildingNumber: "B-402",
  censusHouseNumber: "01",
  headName: "Rajesh Kumar",
  headGender: "male",
  socialCategory: "Other",
  mobileNumber: "9876543210",
  floorMaterial: "mosaic_tiles",
  wallMaterial: "burnt_brick",
  roofMaterial: "concrete_rcc",
  houseUse: "residential",
  houseCondition: "good",
  householdTotalPersons: 4,
  ownershipStatus: "owned",
  dwellingRooms: 3,
  marriedCouplesCount: 1,
  drinkingWaterSource: "tap_treated",
  waterAvailability: "within_premises",
  lightingSource: "electricity",
  latrineFacility: "flush_piped",
  drainageType: "closed_drain",
  bathingFacility: "attached_bathroom",
  kitchenFacility: "cooking_inside_lpg",
  cookingFuel: "lpg_png",
  hasRadio: "yes",
  hasTv: "yes",
  hasInternet: "yes",
  hasLaptop: "yes",
  hasPhone: "yes",
  hasVehicle: "four_wheeler",
  casteSubCategory: "General",
};

/** Default household members for a pre-filled practice session */
export const DEFAULT_MEMBERS = [
  {
    id: "m-1",
    name: "Rajesh Kumar",
    relation: "Head",
    gender: "Male",
    age: 42 as number | string,
    maritalStatus: "Currently Married",
    isLiterate: "yes",
    casteCategory: "General",
  },
  {
    id: "m-2",
    name: "Sunita Kumar",
    relation: "Spouse",
    gender: "Female",
    age: 39 as number | string,
    maritalStatus: "Currently Married",
    isLiterate: "yes",
    casteCategory: "General",
  },
];
