import { db, EnumerationDraft } from "../db/store";
import { HLO_31_QUESTIONS } from "../db/seed-data";
import { logSecurityEvent } from "../security/security-logger";

/**
 * An inconsistency alert generated by the Census rule validation engine.
 */
export interface InconsistencyWarning {
  fieldId: string;
  type: "warning" | "error";
  message: string;
  recommendation: string;
}

/**
 * Security exception thrown when an authenticated caller attempts to access
 * or mutate a draft belonging to a different user (Insecure Direct Object Reference).
 */
export class IdorSecurityError extends Error {
  constructor(message: string = "Access denied. You do not own this resource.") {
    super(message);
    this.name = "IdorSecurityError";
  }
}

/**
 * Core business service managing Census practice enumeration drafts,
 * zero-trust ownership checks, and demographic consistency validation.
 */
export const enumerationService = {
  /**
   * Retrieves official questionnaire schema for the given Census phase.
   *
   * @param phase - 1 for House Listing (HLO), 2 for Population Enumeration (PE)
   * @param lang - Target language code
   * @returns Phase metadata and question list
   */
  getQuestions(phase: 1 | 2 = 1, _lang: string = "en") {
    if (phase === 1) {
      return {
        phase: 1,
        title: "House Listing & Housing Census (HLO)",
        totalQuestions: HLO_31_QUESTIONS.length,
        questions: HLO_31_QUESTIONS,
      };
    }
    return {
      phase: 2,
      title: "Population Enumeration & Caste Census (PE)",
      totalQuestions: 14,
      questions: [],
    };
  },

  /**
   * Initializes a new practice enumeration draft for a user.
   *
   * @param userId - Owner user identifier
   * @param stateCode - 2-letter Indian state/UT code
   * @param phase - Census phase (1 = HLO, 2 = PE)
   * @returns Newly created draft object
   */
  async createDraft(userId: string, stateCode: string, phase: 1 | 2 = 1): Promise<EnumerationDraft> {
    const draftId = `draft_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const newDraft: EnumerationDraft = {
      id: draftId,
      userId,
      stateCode: stateCode.toUpperCase(),
      phase,
      step: 1,
      status: "draft",
      payload: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await db.saveDraft(newDraft);
    await db.addAuditLog(userId, "CREATE_DRAFT", `draft:${draftId}`);
    return newDraft;
  },

  /**
   * Enforces zero-trust ownership: caller must own draft.
   *
   * @param id - Draft unique ID
   * @param userId - Caller user ID from authenticated session
   * @param clientIp - Client IP for audit logging
   * @returns Draft object if found and owned by caller
   * @throws {IdorSecurityError} If draft exists but belongs to a different user
   */
  async getDraft(id: string, userId: string, clientIp: string = "127.0.0.1"): Promise<EnumerationDraft | null> {
    const draft = await db.getDraft(id);
    if (!draft) return null;

    if (draft.userId !== userId) {
      logSecurityEvent({
        eventType: "IDOR_ACCESS_DENIED",
        actorId: userId,
        ip: clientIp,
        endpoint: `/api/v1/enumeration/drafts/${id}`,
        details: `Unauthorized attempt to access draft belonging to user '${draft.userId}'`,
      });
      throw new IdorSecurityError(`Access denied: You do not have permission to view draft '${id}'.`);
    }

    return draft;
  },

  /**
   * Updates an existing practice draft with step progress and partial answers.
   *
   * @param id - Draft unique ID
   * @param userId - Caller user ID
   * @param step - Current wizard step (1-5)
   * @param partialPayload - Updated form fields
   * @param clientIp - Client IP for audit logs
   * @returns Updated draft object
   * @throws {IdorSecurityError} If caller is not the owner
   */
  async patchDraft(
    id: string,
    userId: string,
    step: number,
    partialPayload: Record<string, any>,
    clientIp: string = "127.0.0.1"
  ): Promise<EnumerationDraft | null> {
    const draft = await db.getDraft(id);
    if (!draft) return null;

    if (draft.userId !== userId) {
      logSecurityEvent({
        eventType: "IDOR_ACCESS_DENIED",
        actorId: userId,
        ip: clientIp,
        endpoint: `/api/v1/enumeration/drafts/${id}`,
        details: `Unauthorized attempt to modify draft belonging to user '${draft.userId}'`,
      });
      throw new IdorSecurityError(`Access denied: You do not have permission to modify draft '${id}'.`);
    }

    draft.step = step;
    draft.payload = { ...draft.payload, ...partialPayload };
    draft.updatedAt = new Date().toISOString();

    await db.saveDraft(draft);
    return draft;
  },

  /**
   * Deletes a practice draft (DPDP Act right-to-erasure / voluntary cleanup).
   *
   * @param id - Draft unique ID
   * @param userId - Caller user ID
   * @param clientIp - Client IP for audit logs
   * @returns True if draft was deleted
   * @throws {IdorSecurityError} If caller is not the owner
   */
  async deleteDraft(id: string, userId: string, clientIp: string = "127.0.0.1"): Promise<boolean> {
    const draft = await db.getDraft(id);
    if (!draft) return false;

    if (draft.userId !== userId) {
      logSecurityEvent({
        eventType: "IDOR_ACCESS_DENIED",
        actorId: userId,
        ip: clientIp,
        endpoint: `/api/v1/enumeration/drafts/${id}`,
        details: `Unauthorized attempt to delete draft belonging to user '${draft.userId}'`,
      });
      throw new IdorSecurityError(`Access denied: You do not have permission to delete draft '${id}'.`);
    }

    return db.deleteDraft(id, userId);
  },

  /**
   * Finalizes a practice draft into a completed simulation with a mock Practice Reference ID.
   *
   * @param id - Draft unique ID
   * @param userId - Caller user ID
   * @param clientIp - Client IP for audit logs
   * @returns Finalized draft, mock reference ID, and summary slip metadata
   * @throws {IdorSecurityError} If caller is not the owner
   */
  async submitDraft(
    id: string,
    userId: string,
    clientIp: string = "127.0.0.1"
  ): Promise<{ draft: EnumerationDraft; practiceReferenceId: string; summary: any } | null> {
    const draft = await db.getDraft(id);
    if (!draft) return null;

    if (draft.userId !== userId) {
      logSecurityEvent({
        eventType: "IDOR_ACCESS_DENIED",
        actorId: userId,
        ip: clientIp,
        endpoint: `/api/v1/enumeration/drafts/${id}/submit`,
        details: `Unauthorized attempt to submit draft belonging to user '${draft.userId}'`,
      });
      throw new IdorSecurityError(`Access denied: You do not have permission to submit draft '${id}'.`);
    }

    const randomSuffix = Math.floor(100000 + Math.random() * 900000);
    const stateCode = draft.stateCode || "IN";
    const practiceReferenceId = `CEN27-${stateCode}-${randomSuffix}`;

    draft.status = "submitted";
    draft.referenceId = practiceReferenceId;
    draft.submittedAt = new Date().toISOString();
    draft.updatedAt = new Date().toISOString();

    await db.saveDraft(draft);
    await db.addAuditLog(userId, "SUBMIT_PRACTICE_SELF_ENUMERATION", `draft:${id}`, `ref:${practiceReferenceId}`);

    return {
      draft,
      practiceReferenceId,
      summary: {
        referenceId: practiceReferenceId,
        stateCode: draft.stateCode,
        submissionDate: draft.submittedAt,
        headOfHousehold: draft.payload.headName || "Practice Respondent",
        totalMembers: draft.payload.totalPersons || 1,
        isSimulation: true,
        verificationNotice:
          "This is a simulated Practice Reference ID for awareness. Share this ID with your enumerator or use it on censusindia.gov.in.",
      },
    };
  },

  /**
   * Rule-based consistency validator detecting demographic anomalies across household fields.
   * Checks:
   * 1. Minor marriage age (<18 currently married)
   * 2. Toddler literacy (<5 years marked literate)
   * 3. Minor head of household (<18)
   * 4. Married couple count vs total household persons (2x couples > total)
   * 5. Cooking fuel vs kitchen connection mismatch
   *
   * @param payload - Complete or partial household payload
   * @returns Array of identified warnings and errors with actionable recommendations
   */
  validateConsistency(payload: Record<string, any>): InconsistencyWarning[] {
    const warnings: InconsistencyWarning[] = [];

    // Check 1: Age vs Marital Status
    if (payload.members && Array.isArray(payload.members)) {
      payload.members.forEach((m: any, idx: number) => {
        const memberName = m.name || `Member #${idx + 1}`;
        if (m.age !== undefined && Number(m.age) < 18 && m.maritalStatus === "currently_married") {
          warnings.push({
            fieldId: `member_${idx}_maritalStatus`,
            type: "warning",
            message: `${memberName} is listed as age ${m.age} with marital status 'Currently Married'.`,
            recommendation: "Please verify if the age or marital status was entered by mistake (Legal marriage age is 18/21).",
          });
        }
        if (m.age !== undefined && Number(m.age) < 5 && m.isLiterate === "yes") {
          warnings.push({
            fieldId: `member_${idx}_literacy`,
            type: "warning",
            message: `${memberName} is under 5 years old and marked as Literate.`,
            recommendation: "Per Census guidelines, children under age 7 are enumerated without formal literacy status.",
          });
        }
      });
    }

    // Check 2: Head of Household Age
    if (payload.headAge !== undefined && Number(payload.headAge) < 18) {
      warnings.push({
        fieldId: "headAge",
        type: "warning",
        message: `Head of household is listed as ${payload.headAge} years old (minor).`,
        recommendation: "Ensure this is an independent household headed by an adult or an unaccompanied minor.",
      });
    }

    // Check 3: Total Persons vs Married Couples
    if (payload.totalPersons && payload.marriedCouples) {
      const total = Number(payload.totalPersons);
      const couples = Number(payload.marriedCouples);
      if (couples * 2 > total) {
        warnings.push({
          fieldId: "marriedCouples",
          type: "error",
          message: `${couples} married couples requires at least ${couples * 2} persons, but total persons is ${total}.`,
          recommendation: "Adjust total persons or count of married couples living together.",
        });
      }
    }

    // Check 4: Cooking inside without ventilation/fuel match
    if (payload.kitchenStatus === "cooking_inside_lpg" && payload.cookingFuel === "firewood") {
      warnings.push({
        fieldId: "cookingFuel",
        type: "warning",
        message: "You selected LPG kitchen connection but listed Firewood as primary cooking fuel.",
        recommendation: "If LPG is primary, select 'LPG / PNG' as the main fuel.",
      });
    }

    return warnings;
  },
};
